Spinner, new Orientation key
mdavisprog/OctaneGUI pull request #9
Opened 2022-08-20 19:11 UTC by thnom

Addition of an `Orientation` key for Spinner to allow for vertical up/down, still defaults to `Horizontal` as per https://github.com/mdavisprog/OctaneGUI/commit/4483bffe1b0e1d667dbd6b004bac928f079ae107

<img width="189" alt="Screenshot 2022-08-20 at 20 09 55" src="https://user-images.githubusercontent.com/56652672/185762737-bbd01a65-63e6-4c57-8543-010c28f052d3.png">

2022-08-24 18:33 UTC, mdavisprog commented
Checking in to see if you have seen my reviews of this pull request. Just want to confirm you have seen these and make sure I haven't missed anything on my end.

2022-08-24 19:54 UTC, thnom commented
Oh apologies, I had not! Thought you were stacked with commits on your branch. Will take a look

2022-08-24 20:08 UTC, thnom reviewed
Am I right in thinking that nothing has changed from my initial commit?

2022-08-24 22:46 UTC, mdavisprog commented
That is correct. I have only added comments to the pull request.

2022-08-25 18:28 UTC, thnom commented
> That is correct. I have only added comments to the pull request.

👍, nothing for me to do then. I marked my review as done yesterday

2022-08-25 23:26 UTC, mdavisprog requested changes

2022-08-25 23:26 UTC, mdavisprog commented on Source/OctaneGUI/Controls/Spinner.h
> +#include "VerticalContainer.h"
I think this header should be moved to the implementation file to reduce the amount of includes required.

2022-08-25 23:26 UTC, mdavisprog commented on Source/OctaneGUI/Controls/Spinner.cpp
> +    if (Root.Contains("Orientation") && strcmp(Root["Orientation"].String(),"Vertical") == 0)
There is a `ToOrientation` function in Control.h that can convert a string to the proper enum. The OnLoad function should do something similar to the above `SetValue` function:

```cpp
m_ButtonOrientation = ToOrientation(Root["Orientation"].String());
```

2022-08-25 23:26 UTC, mdavisprog commented on Source/OctaneGUI/Controls/Spinner.cpp
> +        m_ButtonOrientation = Orientation::Vertical;
The orientation is now set above. Can be removed.

2022-08-25 23:26 UTC, mdavisprog commented on Source/OctaneGUI/Controls/Spinner.h
> +    std::shared_ptr<Container> m_ButtonContainer { nullptr };
Could change this to a BoxContainer. Will need a forward declaration above.

2022-08-25 23:26 UTC, mdavisprog commented on Source/OctaneGUI/Controls/Spinner.cpp
> +        std::static_pointer_cast<VerticalContainer>(m_ButtonContainer)->SetSpacing(Vector2{0.0f,0.0f});
With m_ButtonContainer change to BoxContainer, this cast won't be needed.

2022-08-25 23:26 UTC, mdavisprog commented on Source/OctaneGUI/Controls/Spinner.cpp
> +
The above should be moved to a separate function. The Splitter class does something similar. This will allow for this layout update to be called from multiple places like `OnLoad` and a `SetOrientation`.

There should also be a 'SetOrientation/GetOrientation' function what will properly update the layout if the value changes.

2022-08-25 23:27 UTC, mdavisprog commented
Sorry, I had made a mistake on my end. The reviews should be viewable now.

2022-08-27 21:02 UTC, closed without merging

2022-08-27 21:30 UTC, thnom commented
See https://github.com/mdavisprog/OctaneGUI/pull/10